### ISSUE TITLE
[BUG]: Unable to run stage 1 with FastSpeech2

### ISSUE THREAD

**Issue by caigun** [open-mmlab/Amphion#111]
## Describe the bug
I followed the tutorials for the example recipe of FastSpeech2 and didn't pass the first stage.
This problem also occurs on my Windows laptop.

## How To Reproduce
1. Config/File changes: Only the local path of the dataset
2. Run command: sh egs/tts/FastSpeech2/run.sh --stage 1

## Expected behavior
Data Preparation failed and was interrupted.

## Screenshots
See error:
(Amphion) harrywang@Harrys-MacBook-Air Amphion % sh egs/tts/FastSpeech2/run.sh --stage 1
/Users/harrywang/Amphion/mfa
Exprimental Configuration File: /Users/harrywang/Amphion/egs/tts/FastSpeech2/exp_config.json
Preprocess LJSpeech...
Prepare alignment LJSpeech...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/harrywang/Amphion/bins/tts/preprocess.py", line 244, in <module>
    main()
  File "/Users/harrywang/Amphion/bins/tts/preprocess.py", line 240, in main
    preprocess(cfg, args)
  File "/Users/harrywang/Amphion/bins/tts/preprocess.py", line 112, in preprocess
    prepare_align(
  File "/Users/harrywang/Amphion/preprocessors/processor.py", line 104, in prepare_align
    ljspeech.prepare_align(dataset, dataset_path, cfg, output_path)
  File "/Users/harrywang/Amphion/preprocessors/ljspeech.py", line 139, in prepare_align
    wav, _ = librosa.load(wav_path, sampling_rate)
__TypeError: load() takes 1 positional argument but 2 were given__

## Environment Information
 - Operating System: MacOS 14.2.1 (problem also occur on Windows 11)
 - Python Version: Python 3.9.15

**Comment by lmxue** [comment]
Hi, what version of librosa are you using?

**Comment by caigun** [comment]
0.10.1

**Comment by lmxue** [comment]
Would you please give the log of the `wav_path` and `sampling_rate` in your experiment?
