### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data\\metadata\\libritts\\train-clean-100#1970#28415#1970_28415_000067_000000.pkl'[Help]: 

### ISSUE THREAD

**Issue by a897456** [open-mmlab/Amphion#172]
E:\ProgramData\anaconda3\envs\py39\python.exe "E:/Program Files/JetBrains/PyCharm 2023.2.4/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 61010 --file E:\00\Amphion-main\bins\tts\train.py 
已连接到 pydev 调试器(内部版本号 232.10203.26)Monotonic align not found. Please make sure you have compiled it.
Use Dynamic Batchsize......
metadata len:  33236
[[26925, 26926, 26927, 26928, 26929, 26930, 26931, 26932]]
metadata len:  0
E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Monotonic align not found. Please make sure you have compiled it.
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\ProgramData\anaconda3\envs\py39\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\00\Amphion-main\models\tts\naturalspeech2\ns2_dataset.py", line 195, in __getitem__
    with open(metadata_uid_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data\\metadata\\libritts\\train-clean-100#1970#28415#1970_28415_000067_000000.pkl'

python-BaseException

进程已结束，退出代码为 1

Hi @HeCheng0625 
sorry, I am a novice, I am replreplying NS2, I have completed `preprocess.py`, and I have also obtained `train.json` and `valid.json`.
So I started to run `train.py`, but I encountered this error, I obviously followed the instructions step by step, I don't know why the error occurred? 
Can you help me?

**Comment by HeCheng0625** [comment]
Hi, it seems that the system did not find the files required for training. Have you generated the ".pkl" files required for training? Furthermore, our system has not been experimented under Windows framework.

**Comment by yuantuo666** [comment]
Hi, @a897456; our system still does not support Windows; you are recommended to run it on an actual Linux system. You can check this pull for new updates about this: https://github.com/open-mmlab/Amphion/pull/136

**Comment by a897456** [comment]
> Hi, it seems that the system did not find the files required for training. Have you generated the ".pkl" files required for training? 

How to generate the ".pkl" files？It doesn't seem to be mentioned in the code
