### ISSUE TITLE
Issue Running FastSpeech2 Model - FileNotFoundError: 'data/LJSpeech/valid.json'

### ISSUE THREAD

**Issue by my-yy** [open-mmlab/Amphion#23]
Hi, thank you for developing this excellent project.

I am attempting to execute the FastSpeech2 model using the provided instructions at:
https://github.com/open-mmlab/Amphion/tree/main/egs/tts/FastSpeech2

Upon running the process command `sh egs/tts/FastSpeech2/run.sh --stage 1`, I encountered the following error: `FileNotFoundError: [Errno 2] No such file or directory: 'data/LJSpeech/valid.json'`.

Could you please provide guidance on resolving this issue? Your assistance is much appreciated.

Full log:
```
(amphion) root@5d89psego5dhs-0:/zhangpai21/workspace/cgy/1_projects/7_Amphion# sh egs/tts/FastSpeech2/run.sh --stage 1
/zhangpai21/workspace/cgy/1_projects/7_Amphion/mfa
Exprimental Configuration File: /zhangpai21/workspace/cgy/1_projects/7_Amphion/egs/tts/FastSpeech2/exp_config.json
Preprocess LJSpeech...
Prepare alignment LJSpeech...
13100it [00:01, 10765.15it/s]
MFA results are save in data/LJSpeech/TextGrid
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 13100.0
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
Calculating CMVN...
Done with setup.
Done! Everything took 1712.1863117218018 seconds
----------
Dataset splits for LJSpeech...

No Data Augmentation.
----------
Preparing metadata...
Including: 
LJSpeech

  0%|                                                                                                                                 | 0/1 [00:00<?, ?it/s]Singer LJSpeech_LJSpeech: 1363.67 mins for training
---------- 

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.77it/s]
Extracting acoustic features for LJSpeech using 4 workers ...
types:  ['train', 'valid', 'test']
Traceback (most recent call last):
  File "/zhangpai21/workspace/cgy/1_projects/7_Amphion/bins/tts/preprocess.py", line 250, in <module>
    main()
  File "/zhangpai21/workspace/cgy/1_projects/7_Amphion/bins/tts/preprocess.py", line 246, in main
    preprocess(cfg, args)
  File "/zhangpai21/workspace/cgy/1_projects/7_Amphion/bins/tts/preprocess.py", line 178, in preprocess
    extract_acoustic_features(dataset, output_path, cfg, args.num_workers)
  File "/zhangpai21/workspace/cgy/1_projects/7_Amphion/bins/tts/preprocess.py", line 44, in extract_acoustic_features
    with open(dataset_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/LJSpeech/valid.json'
```

**Comment by lmxue** [comment]
We will fix the bug as soon as possible.
