### ISSUE TITLE
[BUG]: [NaturalSpeech2] AttributeError: 'JsonHParams' object has no attribute 'diffusion_type'

### ISSUE THREAD

**Issue by cantabile-kwok** [open-mmlab/Amphion#256]
## Describe the bug
The official config `ns2.json` does not have `diffusion.diffusion_type` attribute. Meanwhile, in `models/tts/naturalspeech2/ns2.py`, it is required.
<img width="445" alt="image" src="https://github.com/user-attachments/assets/7dd943bc-646b-4761-bfef-7bc6812e32ca">

![image](https://github.com/user-attachments/assets/4eafd11d-634d-474f-8e9b-797a3be15f84)

## How To Reproduce
1. Config/File changes: None
2. Run command: `bash egs/tts/NaturalSpeech2/run_inference.sh --text "[The text you want to generate]"`
3. See error: 
```
Traceback (most recent call last):
  File "/tools/Amphion/bins/tts/inference.py", line 169, in <module>
    main()
  File "/tools/Amphion/bins/tts/inference.py", line 162, in main
    inferencer = build_inference(args, cfg)
  File "/tools/Amphion/bins/tts/inference.py", line 29, in build_inference
    inference = inference_class(args, cfg)
  File "/tools/Amphion/models/tts/naturalspeech2/ns2_inference.py", line 29, in __init__
    self.model = self.build_model()
  File "/tools/Amphion/models/tts/naturalspeech2/ns2_inference.py", line 37, in build_model
    model = NaturalSpeech2(self.cfg.model)
  File "/tools/Amphion/models/tts/naturalspeech2/ns2.py", line 31, in __init__
    if cfg.diffusion.diffusion_type == "diffusion":
AttributeError: 'JsonHParams' object has no attribute 'diffusion_type'
```

## Expected behavior
Simply add 
```json
"diffusion_type": "diffusion"
```
into the `ns2.json` config will solve the problem.

**Comment by cantabile-kwok** [comment]
Set `config` to `egs/tts/NaturalSpeech2/exp_config.json` solves this error. It was my mistake.
