### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Serdcoff** [open-mmlab/Amphion#285]
## Description of the bug
(Error when trying to run python main.py)

## Environment Information
 - Operating System: [e.g. Ubuntu 22.04.4 LTS]
 - Python Version: [e.g. Python 3.9.20]
 - Driver & CUDA Version: [Driver Version: 535.183.01   CUDA Version: 12.2]
 - Error Messages and Logs: 
 - [****/anaconda3/envs/AudioPipeline/lib/python3.9/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
****/.local/lib/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
Traceback (most recent call last):
  File "****/Amphion/preprocessors/Emilia/utils/tool.py", line 39, in load_cfg
    cfg = json.load(f)
  File "****/anaconda3/envs/AudioPipeline/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "****/anaconda3/envs/AudioPipeline/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "****/anaconda3/envs/AudioPipeline/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "***/anaconda3/envs/AudioPipeline/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 14 column 9 (char 225)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "****/Amphion/preprocessors/Emilia/main.py", line 493, in <module>
    cfg = load_cfg(args.config_path)
  File "****/Amphion/preprocessors/Emilia/utils/tool.py", line 41, in load_cfg
    raise TypeError(
TypeError: Please finish the `// TODO:` in the `config.json` file before running the script. Check README.md for details.]

## Additional context
(Add any other context about the problem here.)

**Comment by Serdcoff** [comment]
Solved with deleting all comment strings with //
