### ISSUE TITLE
[Help]: RuntimeError: espeak not installed on your system

### ISSUE THREAD

**Issue by chenwei20** [open-mmlab/Amphion#297]
当我在windows上 执行python maskgct_inference.py出现下面的提示 
./models/tts/maskgct/g2p\sources\g2p_chinese_model\poly_bert_model.onnx
E:\Amphion\envs\amphion\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Traceback (most recent call last):
  File "E:\Amphion\models\tts\maskgct\maskgct_inference.py", line 6, in <module>
    from models.tts.maskgct.maskgct_utils import *
  File "E:\Amphion\models\tts\maskgct\maskgct_utils.py", line 26, in <module>
    from models.tts.maskgct.g2p.g2p_generation import g2p, chn_eng_g2p
  File "E:\Amphion\models\tts\maskgct\g2p\g2p_generation.py", line 10, in <module>
    from models.tts.maskgct.g2p.utils.g2p import phonemizer_g2p
  File "E:\Amphion\models\tts\maskgct\g2p\utils\g2p.py", line 17, in <module>
    phonemizer_zh = EspeakBackend(
  File "E:\Amphion\envs\amphion\lib\site-packages\phonemizer\backend\espeak\espeak.py", line 45, in __init__
    super().__init__(
  File "E:\Amphion\envs\amphion\lib\site-packages\phonemizer\backend\espeak\base.py", line 39, in __init__
    super().__init__(
  File "E:\Amphion\envs\amphion\lib\site-packages\phonemizer\backend\base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system
(amphion) PS E:\Amphion>
我已经将espeak在powershell中添加进了Path变量，并且在用户环境变量里也添加好了，为什么还是提示没有安装espeak呢？

**Comment by blues-green** [comment]
linux上也是。请问如何安装？

**Comment by HeCheng0625** [comment]
Hi, try to "sudo apt-get install espeak-ng"?

**Comment by yuantuo666** [comment]
Hi, the MaskGCT is built in a Linux environment. For a better coding experience, it is recommended that Linux be used to reproduce.
Besides, we prefer English issues in this repository.
According to the stack trace, it seems to be the problem with the `phonemizer` package, reading their [docs](https://bootphon.github.io/phonemizer/install.html) might be helpful.

**Comment by yuantuo666** [comment]
For people who are having problem in configuring the env on a Windows machine, you can try to follow this blog post: https://www.cnblogs.com/v3ucn/p/18511187

**Comment by justinjohn0306** [comment]
Windows users can try my fork here: https://github.com/justinjohn0306/MaskGCT-Windows

**Comment by ytlviv** [comment]
I also encountered the same problem, I am mac os, through brew install espeak installation, also reported this error, how to deal with

**Comment by AimForNaN** [comment]
I'm getting the same error on my Linux machine. I tried adjusting env vars for both conda and shell session, but nothing seems to work.

**Comment by AimForNaN** [comment]
Coming across [this issue](https://github.com/bootphon/phonemizer/issues/189), I placed the following code at the top of `gradio_demo.py`:

```py
from phonemizer.backend.espeak.wrapper import EspeakWrapper
EspeakWrapper()
```

Interestingly, this was sufficient to get passed the error. So, it's not so much that it can't find espeak as much as it is that the runtime error message is a lie.

**Comment by reosablo** [comment]
I resolved this problem by setting the path of the espeak dll explicitly in a environment variable [`PHONEMIZER_ESPEAK_LIBRARY`](https://github.com/bootphon/phonemizer/blob/v3.3.0/phonemizer/backend/espeak/wrapper.py#L118-L134).

```winbatch
set PHONEMIZER_ESPEAK_LIBRARY=C:\Program Files\eSpeak NG\libespeak-ng.dll
```

**Comment by notnotsamuel** [comment]
MacOS 
```bash
export PHONEMIZER_ESPEAK_LIBRARY="$(brew --prefix espeak)/lib/libespeak.dylib"
```
