### ISSUE TITLE
[BUG]: RuntimeError: language "cmn" is not supported by the espeak backend

### ISSUE THREAD

**Issue by movvaprasanth** [open-mmlab/Amphion#338]
## Describe the bug
(A clear and concise description of what the bug is.)

It keep saying cmn is not supported, when we try to run the inferencing or the gradio files to test. Installation is done without issues, even tried with "pip install --upgrade phonemizer", "brew install espeak-ng" and "brew install espeak".. it still do not show cmn in the espeak --voices. 

## Environment Information
 - Operating System: MacOS
 - Python Version: 3.12.7

## Error information 
.venv) ...@MacBook-Pro Amphion % python -m models.tts.maskgct.maskgct_inference
./models/tts/maskgct/g2p/sources/g2p_chinese_model/poly_bert_model.onnx
/Users/.../sql-chain/.venv/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:115: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CoreMLExecutionProvider, AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/.../sql-chain/DB/backend/Amphion/models/tts/maskgct/maskgct_inference.py", line 6, in <module>
    from models.tts.maskgct.maskgct_utils import *
  File "/Users/.../sql-chain/DB/backend/Amphion/models/tts/maskgct/maskgct_utils.py", line 20, in <module>
    from models.tts.maskgct.g2p.g2p_generation import g2p, chn_eng_g2p
  File "/Users/.../sql-chain/DB/backend/Amphion/models/tts/maskgct/g2p/g2p_generation.py", line 116, in <module>
    text_tokenizer = PhonemeBpeTokenizer()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../sql-chain/DB/backend/Amphion/models/tts/maskgct/g2p/g2p/__init__.py", line 26, in __init__
    self.int_text_tokenizers()
  File "/Users/.../sql-chain/DB/backend/Amphion/models/tts/maskgct/g2p/g2p/__init__.py", line 36, in int_text_tokenizers
    self.text_tokenizers[key] = TextTokenizer(language=value)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../sql-chain/DB/backend/Amphion/models/tts/maskgct/g2p/g2p/text_tokenizers.py", line 32, in __init__
    self.backend = EspeakBackend(
                   ^^^^^^^^^^^^^^
  File "/Users/.../sql-chain/.venv/lib/python3.12/site-packages/phonemizer/backend/espeak/espeak.py", line 45, in __init__
    super().__init__(
  File "/Users/.../sql-chain/.venv/lib/python3.12/site-packages/phonemizer/backend/espeak/base.py", line 39, in __init__
    super().__init__(
  File "/Users/.../sql-chain/.venv/lib/python3.12/site-packages/phonemizer/backend/base.py", line 86, in __init__
    self._language = self._init_language(language)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/../sql-chain/.venv/lib/python3.12/site-packages/phonemizer/backend/base.py", line 100, in _init_language
    raise RuntimeError(
RuntimeError: language "cmn" is not supported by the espeak backend

**Comment by yuantuo666** [comment]
This problem is related to the `phonemizer` installation.

Duplicate with: https://github.com/open-mmlab/Amphion/issues/297, https://github.com/open-mmlab/Amphion/issues/323
