### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '[M4Singer dataset path]/meta.json'  when running sh egs/svc/MultipleContentsSVC/run.sh --stage 1

### ISSUE THREAD

**Issue by ErLongHuDaoGe** [open-mmlab/Amphion#64]
This is my termunal:
(amphion) ayit@aiexplorer:~/Downloads/Amphion$ sh egs/svc/MultipleContentsSVC/run.sh --stage 1
Exprimental Configuration File: /home/ayit/Downloads/Amphion/egs/svc/MultipleContentsSVC/exp_config.json
Preprocess m4singer...
----------
Preparing test samples for m4singer...

Traceback (most recent call last):
  File "/home/ayit/Downloads/Amphion/bins/svc/preprocess.py", line 182, in <module>
    main()
  File "/home/ayit/Downloads/Amphion/bins/svc/preprocess.py", line 178, in main
    preprocess(cfg, args)
  File "/home/ayit/Downloads/Amphion/bins/svc/preprocess.py", line 83, in preprocess
    preprocess_dataset(
  File "/home/ayit/Downloads/Amphion/preprocessors/processor.py", line 50, in preprocess_dataset
    m4singer.main(output_path, dataset_path)
  File "/home/ayit/Downloads/Amphion/preprocessors/m4singer.py", line 71, in main
    with open(meta_file, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '[M4Singer dataset path]/meta.json'

**Comment by RMSnow** [comment]
Hi @ErLongHuDaoGe , you need to replace the `[M4Singer dataset path]` as the real path of your downloaded M4Singer dataset path.

**Comment by RMSnow** [comment]
Hi @ErLongHuDaoGe, if you have any further questions, feel free to re-open this issue!
